// FILM.TIMELINE: the shot list and audio cue list for "The life of a monarch butterfly".
// Owner: storyboard. Human-readable plan: docs/storyboard.md. Visual rules: docs/art-bible.md.
// 120 bpm: a beat is 0.5 s (12 frames at 24 fps). Every shot boundary sits on the beat grid.
(function () {
  'use strict';
  const FILM = window.FILM;

  FILM.TIMELINE = {
    title: 'The life of a monarch butterfly',
    bpm: 120,
    duration: 32,
    fps: 24,
    width: 1080,
    height: 1920,
    shots: [
      {
        id: 'hero-on-milkweed',
        file: '01-hero-on-milkweed.js',
        start: 0,
        end: 1.5,
        mode: 'illustrated',
        title: 'Cold open: the monarch',
        transitionIn: { kind: 'cut', dur: 0 },
        brief: 'An adult female monarch seen from above, wings flat open on the G5 geometry, perched on a pink common milkweed flower ball over cream and yellow diagonal stripes, and frame 0 is fully drawn. The wings fold up in three drawings and slam down on the 0.5 s beat as yellow and magenta rings burst from the thorax. Female: wide black veins, no hindwing scent spot, four legs down and forelegs folded.',
      },
      {
        id: 'egg-blueprint',
        file: '02-egg-blueprint.js',
        start: 1.5,
        end: 4,
        mode: 'schematic',
        title: 'A spark, an egg',
        transitionIn: { kind: 'cut', dur: 0 },
        brief: 'A white spark on near-black navy threads the micropyle of a lavender blueprint egg hanging under a leaf band (G1: 760 px tall, ribbed, rosette at the downward tip). The single nucleus divides 1, 2, 4, 8 on the beats and 16ths, the nuclei move to the shell wall, and the yolk condenses into a curled larva with its head at the tip. Magenta flashes mark fertilisation, division and the hatch signal.',
      },
      {
        id: 'egg-hatch',
        file: '03-egg-hatch.js',
        start: 4,
        end: 5.5,
        mode: 'illustrated',
        title: 'First meal: the eggshell',
        transitionIn: { kind: 'cut', dur: 0 },
        brief: 'Match cut to the inked ivory egg on the same G1 pixels, glued under a hairy milkweed leaf. The tip cracks, a big black head pushes out, the camera pulls back to zoom 0.45 as the translucent grey-green first instar hauls out, and it bites the eggshell away in two scalloped bites. The larva is shiny and unbanded with a black head wider than its body.',
      },
      {
        id: 'larva-molts',
        file: '04-larva-molts.js',
        start: 5.5,
        end: 8,
        mode: 'illustrated',
        title: 'Four molts up the stem',
        transitionIn: { kind: 'cut', dur: 0 },
        brief: 'A caterpillar climbs a full-height milkweed stem past latex trench rings on the lower leaves and arc holes on the middle leaves. It molts on the four beats 6.0, 6.5, 7.0 and 7.5: the head capsule pops off and lands in a yellow tally ring, the skin slides back and is eaten, and the next instar snaps longer with bolder bands and longer T2 and A8 filaments. A blue ruler and yellow bracket measure the growth from 45 to 430 px.',
      },
      {
        id: 'instar-ladder',
        file: '05-instar-ladder.js',
        start: 8,
        end: 9.5,
        mode: 'schematic',
        title: 'Growth, stored poison, hidden wings',
        transitionIn: { kind: 'cut', dur: 0 },
        brief: 'Five blueprint caterpillar outlines stack up the frame height from 60 to 620 px long, drawing on one per 16th. Milkweed flow lines feed a magenta cardenolide glyph inside the 5th instar and two wing imaginal discs glow behind its head. On the 9.0 beat the 5th instar morphs into the J outline (G2) hanging from the silk pad, ready to match cut.',
      },
      {
        id: 'j-hang',
        file: '06-j-hang.js',
        start: 9.5,
        end: 11.5,
        mode: 'illustrated',
        title: 'The J, then the chrysalis',
        transitionIn: { kind: 'cut', dur: 0 },
        brief: 'The banded 5th instar hangs in a J from a silk pad under a twig, straightens, and ripples. Its skin splits behind the head and scrunches up in three steps as the green form contracts into the jade chrysalis (G3), the cremaster locks into the silk and the black skin drops. The chrysalis twists twice and its gold dots pop on.',
      },
      {
        id: 'inside-chrysalis',
        file: '07-inside-chrysalis.js',
        start: 11.5,
        end: 13,
        mode: 'schematic',
        title: 'Rebuilt, not melted',
        transitionIn: { kind: 'cut', dur: 0 },
        brief: 'The chrysalis as a lavender blueprint on G3, abdomen up and head down. Larval muscle lines break into drifting stipple with magenta flickers, the gut narrows, the nerve cord is kept and shortens, and eye, antenna, leg and wing primordia ignite and wire to four node glyphs down the lower half. Flight-muscle fibres draw on in the thorax as the wing node flashes magenta.',
      },
      {
        id: 'chrysalis-days',
        file: '08-chrysalis-days.js',
        start: 13,
        end: 16,
        mode: 'illustrated',
        title: 'Twelve days by the sun',
        transitionIn: { kind: 'cut', dur: 0 },
        brief: 'The jade chrysalis hangs under a twig while the sun and moon cross a dotted arc once per 8th note for 12 days, the sky stripes cycling day, dusk and night. Each day lights one rim gold dot and fills a slot of a yellow tally ring, and the chrysalis shadow sweeps a sundial on the leaf below. On days 9 to 12 the case darkens and the folded orange and black wings show inside.',
      },
      {
        id: 'eclosion',
        file: '09-eclosion.js',
        start: 16,
        end: 18,
        mode: 'illustrated',
        title: 'Emergence',
        transitionIn: { kind: 'flash', dur: 0.125 },
        brief: 'On the midpoint downbeat a cream flash reveals the adult sliding head first out of the split case and gripping it, head up, abdomen swollen, wings crumpled. Three pumps on the beats send blue pulses along the veins as the closed wings grow to full size on G4, then a red-brown meconium drop falls. Underside colours, forelegs folded, proboscis still in two halves.',
      },
      {
        id: 'wing-veins',
        file: '10-wing-veins.js',
        start: 18,
        end: 19.5,
        mode: 'schematic',
        title: 'Veins as plumbing',
        transitionIn: { kind: 'cut', dur: 0 },
        brief: 'The hanging adult as a lavender blueprint on G4 with white veins drawn from the base out. Waves of hemolymph dots pulse from a pump glyph along every vein on the 8ths while an inset cross-section flattens two pleated membranes. A reticle locks magenta on the forewing margin target and the camera eases 8 percent toward it.',
      },
      {
        id: 'scale-mosaic',
        file: '11-scale-mosaic.js',
        start: 19.5,
        end: 22,
        mode: 'illustrated',
        title: 'Push-in: the wing is a mosaic',
        transitionIn: { kind: 'cut', dur: 0 },
        brief: 'Match cut to the inked wing, then an exponential push-in to 40x on the target, landing zoom steps on the beats. Flat colour breaks into tiles and resolves into shingled scales, each one flat colour with ridges, orange cell above, a black vein band across and a white spot below. One scale lifts on its stalk under a screen-fixed yellow ring, blue row guides and a shrinking scale bar.',
      },
      {
        id: 'sun-compass',
        file: '12-sun-compass.js',
        start: 22,
        end: 23.5,
        mode: 'schematic',
        title: 'A clock in the antennae',
        transitionIn: { kind: 'cut', dur: 0 },
        brief: 'A blueprint monarch head from above under a sky dome, with a clock dial in each antenna club and a compass below. The sun steps across the dome on the beats, the antenna clock hands tick and the angle arc redraws, while the magenta south-west heading line never moves. On 23.0 the heading extends off the lower-left edge, setting the screen direction for the migration.',
      },
      {
        id: 'pull-back-continent',
        file: '13-pull-back-continent.js',
        start: 23.5,
        end: 26.5,
        mode: 'illustrated',
        title: 'Pull-back: leaf, plant, meadow, continent',
        transitionIn: { kind: 'cut', dur: 0 },
        brief: 'One log-linear zoom out through five ink layers landing on beats: the open-winged female on a leaf, the whole autumn milkweed with split seed pods, a meadow, farmland, then a map of eastern North America on the G6 projection. Shrinking yellow frame rectangles trail the scale jump and a blue line follows her south-west. Hundreds of orange dots stream from the northern band through Texas into a magenta ring on Michoacán.',
      },
      {
        id: 'migration-column',
        file: '14-migration-column.js',
        start: 26.5,
        end: 28,
        mode: 'illustrated',
        title: 'The column heads south-west',
        transitionIn: { kind: 'cut', dur: 0 },
        brief: 'A column of about 260 monarchs streams from the top right down to the lower left, small and far at the top and large near the viewer, over hatched hills with fir mountains at the bottom. A low sun sits on the dotted sun-path arc with a blue sun-angle annotation to the lead butterfly. Waves of new butterflies enter on the beats.',
      },
      {
        id: 'oyamel-winter',
        file: '15-oyamel-winter.js',
        start: 28,
        end: 29.5,
        mode: 'illustrated',
        title: 'Winter on the firs',
        transitionIn: { kind: 'cut', dur: 0 },
        brief: 'Night in an oyamel fir forest: three trunks, the middle one shingled with resting monarchs and dead-leaf clusters sagging from the branches, frost stipple and mist bands. Five moons appear on the 8ths to count the winter months. On 29.25 the sky flashes to dawn, a magenta arrow flips from south-west to north-east, and the clusters burst up and to the right.',
      },
      {
        id: 'spring-egg',
        file: '16-spring-egg.js',
        start: 29.5,
        end: 30.5,
        mode: 'illustrated',
        title: 'Spring: a new egg',
        transitionIn: { kind: 'cut', dur: 0 },
        brief: 'The worn, faded female clings under a young spring milkweed leaf and drums it with her forelegs on four 16ths, yellow rings pulsing. On 30.0 she lays a 16 px egg under the leaf, and a snap zoom to 47x about (540, 900) lands it exactly on the G1 outline. Her wings show a notch and bare patches of missing scales.',
      },
      {
        id: 'egg-loop',
        file: '17-egg-loop.js',
        start: 30.5,
        end: 32,
        mode: 'schematic',
        title: 'Back to the egg',
        transitionIn: { kind: 'cut', dur: 0 },
        brief: 'The egg-blueprint composition on the same pixels with one glowing nucleus, fully drawn on the first frame. The cycle glyph resets to the egg arc and the lowercase wordmark monarch fades in centred at y 1470, then the nucleus divides into two with a magenta flash. The last frame loops straight into the hero cold open.',
      },
    ],
    cues: [
      { t: 0, kind: 'hit', note: 'Bar 1 downbeat: felt kick, FM marimba D major add9 chord, sine sub D2' },
      { t: 0.083, kind: 'sfx', note: 'Rising wing flutter, band-passed noise sweeping up' },
      { t: 0.5, kind: 'hit', note: 'Wing slam: downward whoosh and sub drop as rings burst; kalimba motif D5 F#5 A5 E5 starts on 8ths' },
      { t: 1, kind: 'sfx', note: 'Small wing-lift flutter' },
      { t: 1.5, kind: 'cut', note: 'Everything drops out: glassy sine ping D6 with long generated reverb for the spark' },
      { t: 2, kind: 'swell', note: 'Reverse swell under the egg outline draw' },
      { t: 2, kind: 'sfx', note: 'Spark threads the micropyle: sine glide 3 kHz to 1.2 kHz over 250 ms' },
      { t: 2.5, kind: 'sfx', note: 'Rising 16th bell arpeggio, D major pentatonic, tracking the lattice sweep' },
      { t: 3, kind: 'sfx', note: 'Division: two pings A5 and D6' },
      { t: 3.25, kind: 'sfx', note: 'Division: four pings in 32nds' },
      { t: 3.5, kind: 'sfx', note: 'Division: eight-ping ripple' },
      { t: 3.75, kind: 'sfx', note: 'Hatch signal crackle: three high-passed noise clicks' },
      { t: 4, kind: 'cut', note: 'Bar 3: woody tock and warm pluck chord return (illustrated timbre)' },
      { t: 4.5, kind: 'hit', note: 'Shell crack: filtered-noise crack with pitched pop A4, then lowpassed whoosh across the pull-back' },
      { t: 5, kind: 'sfx', note: 'Bite: 20 ms band-passed noise at 2.5 kHz through a woody resonator, scatter ticks' },
      { t: 5.25, kind: 'sfx', note: 'Second bite, slightly lower' },
      { t: 5.5, kind: 'cut', note: 'Chew clicks on 16ths L/R; three wet latex plips on 5.5, 5.625, 5.75' },
      { t: 6, kind: 'hit', note: 'Molt 1: FM boop D4 with up-bend, crinkle burst, capsule click A5, kick' },
      { t: 6.5, kind: 'hit', note: 'Molt 2: boop F#4, crinkle, capsule click F#5' },
      { t: 7, kind: 'hit', note: 'Molt 3: boop A4, crinkle, capsule click D5, kick; shaker 8ths enter' },
      { t: 7.5, kind: 'hit', note: 'Molt 4: boop D5, crinkle, capsule click A4' },
      { t: 8, kind: 'cut', note: 'Bar 5: five rising glass bell ticks on 16ths over a sub swell' },
      { t: 8.5, kind: 'sfx', note: 'Cardenolide: short detuned magenta stab, two band-passed saws' },
      { t: 8.75, kind: 'sfx', note: 'Wing discs ignite: soft FM bell' },
      { t: 9, kind: 'sfx', note: 'Downward pitch-bend whoosh as the body curls into the J' },
      { t: 9.5, kind: 'cut', note: 'Tock and pluck' },
      { t: 10, kind: 'sfx', note: 'Low stretching creak as the body straightens' },
      { t: 10.5, kind: 'sfx', note: 'Skin tear: bandpass noise 400 Hz to 4 kHz over 200 ms; descending plucks A4 F#4 D4 on 10.5, 10.75, 11.0' },
      { t: 11, kind: 'sfx', note: 'Cremaster clack, soft thud and falling whistle as the skin drops' },
      { t: 11.25, kind: 'sfx', note: 'Cascade of metallic FM tings for the gold dots' },
      { t: 11.5, kind: 'cut', note: 'Drums out: low-passed pad swell with granular crackle as muscles break' },
      { t: 12, kind: 'sfx', note: 'Descending filter sweep; paired bells D5 A5 on the ignite 16ths' },
      { t: 12.5, kind: 'hit', note: 'Magenta chime with shimmer; rising striated buzz, saw through comb filter' },
      { t: 13, kind: 'cut', note: 'Clock motif: woodblock tick and a glockenspiel note per 8th, climbing D major over 12 days' },
      { t: 15, kind: 'swell', note: 'Shimmer riser starts: noise sweep plus tremolo sine; heartbeat kick on quarters' },
      { t: 15.5, kind: 'sfx', note: 'Heartbeat doubles to 8ths under the magenta pulse' },
      { t: 15.75, kind: 'swell', note: 'Heartbeat 16ths and reverse cymbal into bar 9' },
      { t: 16, kind: 'cut', note: 'Cream flash cut into emergence' },
      { t: 16, kind: 'hit', note: 'Bar 9 midpoint drop: kick, open D major chord bloom (saw pad, plucks, sub), big reverb; shell crack and creak' },
      { t: 16.5, kind: 'sfx', note: 'Pump 1: 55 Hz sine whump with rising sweep, paper crinkle; hi-hat 8ths start' },
      { t: 17, kind: 'sfx', note: 'Pump 2, louder; lead pluck melody enters' },
      { t: 17.5, kind: 'sfx', note: 'Pump 3, loudest' },
      { t: 17.75, kind: 'sfx', note: 'Meconium drip: sine dropping from 300 Hz' },
      { t: 18, kind: 'cut', note: 'Bar 10: glass ping' },
      { t: 18.5, kind: 'sfx', note: 'Hemolymph pulse bell D5 with delay' },
      { t: 18.75, kind: 'sfx', note: 'Pulse bell E5' },
      { t: 19, kind: 'sfx', note: 'Pulse bell F#5; 60 ms square-wave lock-on bleep' },
      { t: 19.25, kind: 'swell', note: 'Pulse bell A5; soft inhale swell into the push-in' },
      { t: 19.5, kind: 'cut', note: 'Rising filtered-noise whoosh with accelerating 16th ticks across the push' },
      { t: 20.5, kind: 'sfx', note: 'Granular shatter: dozens of tiny panned clicks as tiles appear' },
      { t: 21, kind: 'hit', note: 'Glassy suspended chord D A E under shimmering high bells' },
      { t: 21.5, kind: 'sfx', note: 'Single tile tick as a scale lifts' },
      { t: 22, kind: 'cut', note: 'Bar 12: glass ping; clock bell with soft FM gong; low drone on D' },
      { t: 22.5, kind: 'sfx', note: 'Clock bell and gong as the sun steps' },
      { t: 23, kind: 'sfx', note: 'Clock bell; two-note rising synth horn A3 to D4' },
      { t: 23.5, kind: 'cut', note: 'Long rising pad swell and reverse cymbal; stereo wind bed opens' },
      { t: 24, kind: 'hit', note: 'Bar 13 downbeat: stage hit, kick and pluck, room reverb' },
      { t: 25, kind: 'hit', note: 'Stage hit, larger reverb' },
      { t: 25.5, kind: 'hit', note: 'Stage hit, larger reverb' },
      { t: 26, kind: 'hit', note: 'Bar 14: continent hit, hall reverb; FM lead melody with long glides peaks' },
      { t: 26.25, kind: 'sfx', note: 'Bell on the Michoacán target pulse; granular patter for the streaming dots' },
      { t: 26.5, kind: 'cut', note: 'Granular wing-flutter bed; kalimba motif an octave up with bell counter-line' },
      { t: 27, kind: 'sfx', note: 'Kick; wave of flutter as new butterflies enter; shaker 16ths' },
      { t: 27.5, kind: 'sfx', note: 'Wave of flutter' },
      { t: 28, kind: 'cut', note: 'Bar 15 breakdown: kick and bass out, hushed sine pad, wind; moon bell A5' },
      { t: 28.25, kind: 'sfx', note: 'Moon bell F#5' },
      { t: 28.5, kind: 'sfx', note: 'Moon bell E5' },
      { t: 28.75, kind: 'sfx', note: 'Moon bell D5' },
      { t: 29, kind: 'sfx', note: 'Moon bell B4' },
      { t: 29.25, kind: 'swell', note: 'Dawn burst: rising noise burst, wave of flutter, icy FM bell sweep turning upward' },
      { t: 29.5, kind: 'cut', note: 'Four tiny wooden taps on 16ths, FM at 3.2 kHz' },
      { t: 30, kind: 'hit', note: 'Egg plip, kick and bass return; reverse whoosh into the cut' },
      { t: 30.5, kind: 'cut', note: 'Glass ping D6, same pitch as the spark' },
      { t: 31, kind: 'hit', note: 'Resolving D major chord with nucleus bells A5 D6' },
      { t: 31.5, kind: 'sfx', note: 'Division chime; final low pluck D2 with long reverb' },
      { t: 31.75, kind: 'sfx', note: 'Soft pickup A4 resolving onto the D of the replay downbeat' },
    ],
  };
})();
